[package]
name = "session-manager"
version = "0.1.0"
edition = "2021"


[dependencies]
simple_kl_rs = {path = "/home/lighttigerxiv/Development/Crates/simple-kl-rs"}
serde_json = "1.0.99"
fuzzy-matcher = "0.3.7"