[package]
name = "com-lighttigerxiv-session-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#simple_kl_rs ={ git = "https://github.com/lighttigerXIV/simple-kl-rs"}
#simple_kl_rs = {path = "/home/lighttigerxiv/Development/Crates/simple-kl-rs"}
simple_kl_rs = {path = "C:\\Users\\lighttigerxiv\\Documents\\Development\\Simple-Keyboard-Launcher\\simple-kl-rs"}
serde = "1.0.181"
serde_yaml = "0.9.25"
fuzzy-matcher = "0.3.7"
open = "5.0.0"
tokio = {version = "1.32.0", features = ["full"]}